### ISSUE TITLE
Plots as an optional dependency?

### ISSUE THREAD

**Issue by Mattriks** [Marco-Congedo/FourierAnalysis.jl#22]
How would feel about making Plots.jl an optional dependency? This should be easy to do using [Requires.jl](https://github.com/MikeInnes/Requires.jl).

**Comment by BeastyBlacksmith** [comment]
Why would you want to do this? It would be better to add `RecipesBase` as a dependency and create recipes in this package.

**Comment by Marco-Congedo** [comment]
@Mattriks and @BeastyBlacksmith 
Both ideas seems good to me and independently applicable to improve upon the existing implementation. What Mattriks suggests, if i well understand, is a way not to include the plots.jl unit of FourierAnalysis if package Plots is not installed. This is because on Windows 7 Plots does not install, so as it is now, people working under Windows 7 cannot use the FourierAnalysis package. Requires allows to include the unit plots.jl of FourierAnalysis only if Plots is installed. One problem i see is that Requires asks to identify the required package by its UUID, but this would limit the inclusion of unit plots.jl only if a specific version of the Plots package is registered, whereas it would be desirable that the inclusion happens if whatever version of Plots.jl is installed. Do you know how this can be done?

**Comment by BeastyBlacksmith** [comment]
From my experience having any of the visualization packages as a direct dependency is likely to create a lot of trouble plus it increases the precompilation time of your package unnecessarily.
That is exactly why the [recipe](https://docs.juliaplots.org/latest/recipes/) system is so good, since `RecipesBase` is a very lightweight dependency and it works with all versions of `Plots.jl` and when the time will come also with `Makie.jl`.

**Comment by Marco-Congedo** [comment]
OK, now i see your point.
I will check well `RecipesBase`. Thanks!

**Comment by Marco-Congedo** [comment]
Hello guys,

   i dropped the dependency `Plots.jl` and added a dependency to `RecipesBase.jl` as suggested by @BeastyBlacksmith.
