### ISSUE TITLE
update project dependencies

### ISSUE THREAD

**Issue by Roh-codeur** [Marco-Congedo/FourierAnalysis.jl#53]
Hi

this is a wonderful library indeed, thanks for putting it together. Unfortunately, it seems to downgrade my libs, such as DataFrames to 0.19. I think it is coming from one of the imports. 

do you think its possible to upgrade the project dependencies?

thanks
Rohit

**Comment by Marco-Congedo** [comment]
Hello, 
i updated the dependencies that i could.
I can't update FFTW because any version higher than 1.1.0 causes problems.
Also, the compat section used strict versions and this was constraining.
I am now allowing many more versions, but can't assure anymore it will work as smoothly as before.
Give it a try. I just registered v1.1.3 
If someone wants to fix the problem with FFTW, that would be great as i don't have the time now.

Cheers

**Comment by Roh-codeur** [comment]
sure, I will give it a shot, thanks!

**Comment by Marco-Congedo** [comment]
Hi, I upgraded all dependencies using Julia v1.6.
v 1.2.0 of FourierAnalysis.jl will be registered soon.
Cheers,
