### ISSUE TITLE
Missing FFTW import

### ISSUE THREAD

**Issue by henry2004y** [Marco-Congedo/FourierAnalysis.jl#67]
Hi again,

In the spectra demo, `plan_rfft` comes from `FFTW.jl`, but the package is not imported.

https://github.com/Marco-Congedo/FourierAnalysis.jl/blob/ac11cdac2c53c5b5ed90f7e429f999882759ce82/src/spectra.jl#L158

Just below this line, `Plots.jl` are imported twice.

It's great that these examples are organized in a natural order! However, some parts seem to be independent of each other, and if I blindly copy and paste the whole chunk into the REPL, interesting intermediate outputs are missing. I don't know if there are better ways to handle these demos :thinking:

**Comment by Marco-Congedo** [comment]
Hi, they are somehow meant to be independent, so that chuncks may be copied and pasted without copying the whole code, that is why i sometimes import things again.
Best is to run the [examples .jl files](https://github.com/Marco-Congedo/FourierAnalysis.jl/tree/ac11cdac2c53c5b5ed90f7e429f999882759ce82/examples).
