### ISSUE TITLE
sampling rate requires integer value

### ISSUE THREAD

**Issue by SeverinBang** [Marco-Congedo/FourierAnalysis.jl#81]
I have a time series that I want to analyze, where the sampling time is 1.52 s and the sampling rate is therefore 1/1.52 Hz. Why is the parameter `sr` of `spectrum()` required to have integer value? Did I misunderstand something?

**Comment by Marco-Congedo** [comment]
No, you understood well, `sr` is an integer. You can still use an integer number i guess and adjust the frequency values you get from the `spectra` function a posteriori.

**Comment by SeverinBang** [comment]
Ok, I'll use this as a workaround then. Thanks :)

**Comment by Marco-Congedo** [comment]
Yeah, you can create your own plotting function to plot the spectra (instead of using the recipe provided with the package), or overwrite the `flabels` field of the `Spectra` structure that is created when you invoke the `spectra` function and just use `plot`. Watch out, tools like `f2b` and `b2f` will not work for you, you will have to write your own.

**Comment by wackydoo** [comment]
I understand the workaround, but is the choice to have `sr` restricted to an integer type arbitrary?  Normally in signal processing the sampling rate is a float.  Can you help me understand why you force `sr` to be an integer and resulting an a loss in precision of the frequencies.

**Comment by Marco-Congedo** [comment]
It is just that all machines i have used (for EEG) use integer sampling rates...
